#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_PATH="${1:-${ROOT_DIR}/research_skills/project.toml}"

REPO_SLUG="${RESEARCH_SKILLS_REPO_SLUG:-${GITHUB_REPOSITORY:-}}"
SERVER_URL="${GITHUB_SERVER_URL:-https://github.com}"

derive_repo_slug_from_git() {
  local remote_url
  remote_url="$(git -C "$ROOT_DIR" remote get-url origin 2>/dev/null || true)"
  if [[ "$remote_url" =~ github\.com[:/]([^/]+)/([^/.]+)(\.git)?$ ]]; then
    printf '%s/%s\n' "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
    return 0
  fi
  return 1
}

if [[ -z "$REPO_SLUG" ]]; then
  REPO_SLUG="$(derive_repo_slug_from_git || true)"
fi

if [[ -z "$REPO_SLUG" ]]; then
  echo "[inject-project-toml] warning: unable to determine repo slug; leaving ${OUT_PATH} unchanged" >&2
  exit 0
fi

REMOTE_URL="${SERVER_URL}/${REPO_SLUG}.git"

cat >"$OUT_PATH" <<EOF
# Auto-generated by scripts/inject_project_toml.sh.
# This file may be overwritten during CI builds.
#
# Override upstream at runtime via:
# - CLI:   --repo <owner>/<repo> (or a Git URL)
# - Env:   RESEARCH_SKILLS_REPO=<owner>/<repo>
# - Project config: research-skills.toml / .research-skills.toml

[upstream]
repo = "${REPO_SLUG}"
url = "${REMOTE_URL}"
EOF

echo "[inject-project-toml] wrote: repo=${REPO_SLUG} url=${REMOTE_URL} -> ${OUT_PATH}"

